about/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.about, name='about'),
]

event/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.event, name='event'),
    url(r'^(?P<event_id>[0-9]+)/$', views.detevent, name='detevent'),
]

fos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^register/$', include('web.urls')),
    # url(r'^login_user/$', views.login_user, name='login_user'),
    # url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # url(r'^reviews/', include('reviews.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('web.urls')),
    url(r'^about/$', include('about.urls')),
    url(r'^events/', include('event.urls')),
    url(r'^$','fos.views.home', name='home'),
    # url(r'^register/','fos.views.register', name='register'),
    url(r'^home/$','fos.views.home', name='home'),
    url(r'^contact/$', 'fos.views.contact',name='contact'),

]

about/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

contact/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


# Create your models here.
class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    subject = models.TextField(max_length=200)
    message = models.TextField(max_length=500)
    message_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

event/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=250)
    place = models.CharField(max_length=250)
    short_descr = models.TextField(max_length=500)
    event_image = models.TextField(max_length=200)
    event_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Devent(models.Model):
	event=models.ForeignKey(Event, on_delete=models.CASCADE)
	event_image = models.TextField(max_length=500)
	event_name=models.CharField(max_length=100)
	descr=models.CharField(max_length=1000)

	
	def __str__(self):
		return self.event_name

web/templates/web/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

about/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
# from . import models
# from .models import Post

# Create your views here.

def about(request):
	return render(request,'web/about.html',{})

contact/views.py
from django.shortcuts import render

# Create your views here.

event/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from . import models
from .models import Event
from .models import Devent


# Create your views here.
def event(request):
	all_event=Event.objects.all()
	return render(request,'web/events.html',{'all_event': all_event,})

def detevent(request,event_id):
	event = get_object_or_404(Event , pk=event_id)
	return render(request,'web/dpost.html',{'event':event,})

web/templates/web/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Q Blog Feed" />
    <title>Fos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/cabout.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" id="a1">Fraternity of seekers</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/home">Home</a></li>
            <li class="active"><a href="/about">About</a></li>
            <li><a href="#contact">Photos</a></li>
            <li><a href="#contact">Videos</a></li>
            <li><a href="/events">Events</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- <div class="container">

      <div class="starter-template">
        <h1><br><br>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div> --><!-- /.container -->


    <!-- Main jumbotron for a primary marketing message or call to action -->
    

    <div class="container">
<div class="container">
      <div class="page-header">
        <h1 id=mh1><center><strong>Who we are?</strong></center></h1>
      </div>
      <p class="lead"><h3>Our goal is to inspire the students who are devoted to science for the welfare of society.</h3><br>
      <h4>Innovation happens when people from different background come together, think together and act together, challenge each other & help each other. NO ONE IS STRONGER THAN ALL OF US. In this modern era, no discipline can work in complete isolation. The absolute need of hour is to "generate" and "harness" multidisciplinary expertise. The peculiarity of multidisciplinary expertise is that it can not be learnt from books, internet and newspaper!!! It can only be acquired by actually being with people from different discipline, under one 'UMBRELLA'. And, this is what Fraternity of Seekers is all about!</h4><br><br>
      Technology is a tool. Just like a hammer (not the tool you want to kick out of your fraternity) – it can build or destroy.

<strong>NOTHING</strong> replaces personal contact. But, often smart rushees will do research on fraternities they are considering. These strategies below build from basic and simple to more advanced and impactful.<br>

Get Found! Don’t use chapter designations that only your members know. (Maryland Beta chapter of Sigma Phi Epsilon.) Use both your fraternity name and nickname on Facebook page, website, Twitter, etc. (SAE & Sigma Alpha Epsilon but avoid the Greek letters)

Don’t be “Frat” – Realize that both students & their parents are doing research. If you promote a fratty image you alienate a good percentage of your potential market for no added benefit.<br>

Clean, Simple and Visual – Not a lot of text. Pictures that truly and positively display chapter activities. Someone should learn a little about your a) History b) Purpose & Values c) What you do.

Promote other chapter’s events… and not just sororities! People don’t want to join a gang that then puts a target on their back for other guys to now hate them. There is value in a potential member feeling like they are joining an organization that has good relations with other fraternities as well as sororities. Actively promoting other fraternity and sorority philanthropies shows you have interfraternal friends.<br>

Show your “Why.” Explaining not WHAT you do as a chapter, but WHY you do it is most important. Engaging in this thing called fraternity is about more than just a good time. Telling your story about WHY you put forth so much time and effort. WHY you feel so strongly about your fraternity isn’t caused by the things that you do, but the driving force behind why you do it. If you can share that WHY, you’ll inspire men to join for all the right reasons. And they’ll never be that brother you look at and think, “Oops!”

      </p>
    </div>

    <footer class="footer">
      <hr>
      <footer>
        <p>&copy;   2016 Fraternity of seekers, Ind</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

web/templates/web/ap.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Q Blog Feed" />
    <title>Fos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/custom.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/home" id="a1">Fraternity of seekers</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="/home">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="#contact">Photos</a></li>
            <li><a href="#contact">Videos</a></li>
            <li><a href="/events">Events</a></li>            
            <li><a href="/contact">Contact</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- <div class="container">

      <div class="starter-template">
        <h1><br><br>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div> --><!-- /.container -->


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h2 id="h1">Our goal is to inspire the students who are devoted to science for the welfare of society.</h2><h2 id="h2"><strong>"Knowledge removes the darkness of ignorance in life."</strong><br><br></h2>
        <p id="p1">Innovation happens when people from different background come together, think together and act together, challenge each other & help each other.<strong> NO ONE IS STRONGER THAN ALL OF US</strong>. In this modern era, no discipline can work in complete isolation. The absolute need of hour is to "generate" and "harness" multidisciplinary expertise. The peculiarity of multidisciplinary expertise is that it can not be learnt from books, internet and newspaper!!!
It can only be acquired by actually being with people from different discipline, under one <strong>'UMBRELLA'</strong>.
And, this is what Fraternity of Seekers is all about!</p>
        <p><a class="btn btn-danger" href="/about" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-3">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-1">
       </div>
        <div class="col-md-8">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Fraternity of seekers, India</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

web/templates/web/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Q Blog Feed" />
    <title>Fos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/ccontact.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/home" id="a1">Fraternity of seekers</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/home">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="#contact">Photos</a></li>
            <li><a href="#contact">Videos</a></li>
            <li><a href="/events">Events</a></li>            
            <li class="active"><a href="/contact">Contact</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- <div class="container">

      <div class="starter-template">
        <h1><br><br>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div> --><!-- /.container -->


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-3">

          <br><br><br><br><br><br><br><br>
          <p><strong>Address</strong><br>RPVV,<br>Lajpat Nagar,<br>New Delhi,<br>Delhi,110036<br><br><strong>Give us call</strong><br>+91-95123213312<br>+91-951232134243<br><br><strong>Send us a note</strong><br>fos_world@gmial.com</p>
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-8">
          <h1>Contact Us</h1><br>
          <h4>We are happy to answer any questions you have or provide you with an estimate.Just send us a message in the form below with any question you may have.</h4><br>
          <form>
            <div class="form-group">
    <input type="name" class="form-control" id="name" placeholder="Name">
  </div>
  <div class="form-group">
    <input type="email" class="form-control" id="email" placeholder="Email">
  </div>
  <div class="form-group">
    <input class="form-control" id="subject" placeholder="Subject">
  </div>
  <div class="form-group">
    <textarea class="form-control" rows="7" placeholder="You can write your message here..."></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Attachment</label>
    <input type="file" id="exampleInputFile">
  </div>
  <button type="send" class="btn btn-info">Send</button>
  <button type="reset" class="btn btn-info">Reset</button>
</form>


       </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Fraternity of seekers, Ind</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

web/templates/web/dpost.html
<h1>
	{{event.title}}
</h1>
<ul>
	{% for devent in event.devent_set.all %}
		<li>{{devent.event_name}}<br>{{event.descr}}</li>
	{% endfor %}
</ul>

web/templates/web/events.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Q Blog Feed" />
    <title>Fos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/custom.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/home" id="a1">Fraternity of seekers</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/home">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="#contact">Photos</a></li>
            <li><a href="#contact">Videos</a></li>
            <li class="active"><a href="/events">Events</a></li>            
            <li><a href="/contact">Contact</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- <div class="container">

      <div class="starter-template">
        <h1><br><br>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div> --><!-- /.container -->


    <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="container">
<div class="container">
      <div class="page-header">
        <h1 id=mh1><center><strong>Upcoming Events</strong></center></h1>
        <h2><center>Freternity of seekers</center></h2>
      </div>

    <div class="container">
      <!-- Example row of columns -->
      {% for event in all_event %}
      <div class="row">
        <div class="col-md-3">
          <img src="2.jpg">
        </div>
        <div class="col-md-9">
          <h2>{{event.title}}</h2>
          <span class="glyphicon glyphicon-time" aria-hidden="true">  {{event.event_date}}</span><br>
          <span class="glyphicon glyphicon-map-marker" aria-hidden="true">  {{event.place}}</span><br><br>
          <p>{{event.short_descr}}</p>
          <p><a class="btn btn-default" href="{% url 'detevent' event.id %}" role="button">View details &raquo;</a><br><br><br></p>
       </div>
       <hr>
        {% endfor %}
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Fraternity of seekers, Ind</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

web/templates/web/form.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

web/templates/web/ipost.html
{% load staticfiles %}

<ul>
	{% for event in all_event %}
	<li><a href="{% url 'detevent' event.id %}">{{event.title}}</a></li>
	{% endfor %}
</ul>

web/templates/web/login.html
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="/home/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="/register">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

web/templates/web/register.html
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'web/form.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

web/templates/web/rev.html
<!-- 	{% for post in all %}
	<li>{{post.name}}</li>
	{% endfor %} -->
	{{ all.name }}

web/templates/web/test.html
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'web/form.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}